In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [17]:
raw_shark_df = pd.read_csv("../data/clean_data/clean_data.csv")
shark_df = raw_shark_df.drop(["type"], axis=1)

print(shark_df.head(), "\n")

nonfatal_df = shark_df[shark_df["fatal"] == "N"]
fatal_df = shark_df[shark_df["fatal"] == "Y"]

# compute overall statistics
total_attacks = len(shark_df)
total_fatal = len(fatal_df)
total_nonfatal = len(nonfatal_df)
prop_fatal = total_fatal / total_attacks

print(f"Total number of attacks: {total_attacks}")
print(f"Number of fatal attacks: {total_fatal}")
print(f"Number of nonfatal attacks: {total_nonfatal}")
print(f"Overall fatality rate: {prop_fatal:.2%}")

             country            state  activity  sex   age fatal       time  \
0            bahamas      staniel cay  swimming    m  12.0     N  afternoon
1                usa          florida  swimming    f  17.0     N    morning
2          australia              nsw  swimming    f  35.0     N    morning
3  galapogos islands  santa fe island  swimming    f   NaN     N  afternoon
4                usa          florida  swimming  NaN   NaN     N    morning

       species  year  month
0          NaN   NaN    6.0
1          NaN   NaN    6.0
2  great white   NaN    6.0
3          NaN   NaN    6.0
4         bull   NaN    6.0

Total number of attacks: 5164
Number of fatal attacks: 1273
Number of nonfatal attacks: 3891
Overall fatality rate: 24.65%

In [19]:
country_counts = shark_df.groupby("country").size().to_frame(name="count").reset_index()
country_counts.sort_values(by="count", ascending=False, inplace=True)
country_counts["prop_total"] = country_counts["count"] / total_attacks
top_10_countries = country_counts.head(10)

print(f"Top 10 Countries account for {top_10_countries["prop_total"].sum()}")
top_10_countries

Top 10 Countries account for 0.7937645236250968

              country  count  prop_total
158               usa   1994    0.386135
8           australia   1084    0.209915
131      south africa    413    0.079977
113  papua new guinea    110    0.021301
9             bahamas    109    0.021108
15             brazil    100    0.019365
105       new zealand     95    0.018397
94             mexico     74    0.014330
103     new caledonia     60    0.011619
48               fiji     60    0.011619

In [20]:
filtered_df = shark_df[shark_df["country"].isin(top_10_countries["country"])]

nonfatal_df = filtered_df[filtered_df["fatal"] == "N"]
fatal_df = filtered_df[filtered_df["fatal"] == "Y"]

# compute statistics
total_attacks = len(filtered_df)
total_fatal = len(fatal_df)
total_nonfatal = len(nonfatal_df)
prop_fatal = total_fatal / total_attacks

print(f"Total number of attacks: {total_attacks}")
print(f"Number of fatal attacks: {total_fatal}")
print(f"Number of nonfatal attacks: {total_nonfatal}")
print(f"Overall fatality rate: {prop_fatal:.2%}")

Total number of attacks: 4099
Number of fatal attacks: 780
Number of nonfatal attacks: 3319
Overall fatality rate: 19.03%

In [35]:
state_counts = filtered_df["state"].value_counts().to_frame().reset_index()
top_states = state_counts[state_counts["count"] > 10]
top_states

                    state  count
0                 florida    987
1         new south wales    364
2                  hawaii    276
3              queensland    258
4              california    215
5       western australia    172
6           kwazulu-natal    146
7          south carolina    136
8   eastern cape province    136
9   western cape province    123
10         north carolina     99
11        south australia     81
12             pernambuco     73
13                  texas     68
14          torres strait     68
15               victoria     62
16           north island     46
17           south island     33
18             new jersey     30
19                 oregon     30
20               new york     28
21          abaco islands     27
22               tasmania     25
23         south province     18
24                    nsw     17
25       central province     17
26     northern territory     15
27                alabama     14
28                georgia     14
29              louisiana     13
30               guerrero     13
31   new ireland province     13
32               veracruz     13
33         north province     12
34        madang province     12
35           quintana roo     11
36          massachusetts     11
37            puerto rico     11
38               virginia     11

In [ ]:
filtered_df2 = shark_df[shark_df["state"].isin(top_states["state"])]

nonfatal_df = filtered_df2[filtered_df2["fatal"] == "N"]
fatal_df = filtered_df2[filtered_df2["fatal"] == "Y"]

# compute statistics
total_attacks = len(filtered_df2)
total_fatal = len(fatal_df)
total_nonfatal = len(nonfatal_df)
prop_fatal = total_fatal / total_attacks

print(f"Total number of attacks: {total_attacks}")
print(f"Number of fatal attacks: {total_fatal}")
print(f"Number of nonfatal attacks: {total_nonfatal}")
print(f"Overall fatality rate: {prop_fatal:.2%}")

Total number of attacks: 3702
Number of fatal attacks: 656
Number of nonfatal attacks: 3046
Overall fatality rate: 17.72%

In [ ]:
filtered_df2.to_csv("../data/clean_data/topstates_data.cav", index=False)