In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pymc as pm
import arviz as az

In [20]:
attack_df = pd.read_csv("../data/clean_data/modeling_data.csv")
attack_df.drop(["country", "time", "month", "hemisphere"], axis=1, inplace=True)
print(f"Num attacks: {len(attack_df)}")

attack_df.head()

Num attacks: 3367

               state              activity fatal      species  season
0            florida              swimming     N          NaN  summer
1    new south wales              swimming     N  great white  winter
2            florida              swimming     N         bull  summer
3  western australia          dive fishing     Y  great white  winter
4    new south wales  surfing/bodyboarding     N         bull    fall

In [21]:
# turn fatal into binary variable
attack_df["fatal"] = (attack_df["fatal"] == "Y").astype(int)

# only keep largest activities
activities_to_keep = ["surfing/bodyboarding", "swimming", "wading"]
attack_df = attack_df[attack_df["activity"].isin(activities_to_keep)]

# compute overall statistics
total_attacks = len(attack_df)
total_fatal = len(attack_df[attack_df["fatal"] == 1])
total_nonfatal = len(attack_df[attack_df["fatal"] == 0])
prop_fatal = total_fatal / total_attacks

print(f"Total number of attacks: {total_attacks}")
print(f"Number of fatal attacks: {total_fatal}")
print(f"Number of nonfatal attacks: {total_nonfatal}")
print(f"Overall fatality rate: {prop_fatal:.2%}\n")
attack_df.head()

Total number of attacks: 2460
Number of fatal attacks: 364
Number of nonfatal attacks: 2096
Overall fatality rate: 14.80%

             state              activity  fatal      species  season
0          florida              swimming      0          NaN  summer
1  new south wales              swimming      0  great white  winter
2          florida              swimming      0         bull  summer
4  new south wales  surfing/bodyboarding      0         bull    fall
5           hawaii  surfing/bodyboarding      0          NaN  spring

In [ ]:
coords = {
    "attack": np.arange(len(attack_df))
}

with pm.Model(coords=coords):

    state_obs = pm.Data("state", attack_df["state"], dims="attack")
    species_obs = pm.Data("species", attack_df["species"], dims="attack")
    season_obs = pm.Data("season", attack_df["season"], dims="attack")
    activity_obs = pm.Data("activity", attack_df["activity"], dims="attack")
    fatal_obs = pm.Data("fatal", attack_df["fatal"], dims="attack")